import openai
import mysql.connector
from mysql.connector import Error

# Set your OpenAI API key
openai.api_key = "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"

def get_workout_plan_from_db(retries=3):
    """
    Retrieves user data from the MySQL database and generates a workout plan.

    Args:
        retries (int): Number of retries for the OpenAI API call if it fails.

    Returns:
        str: The workout plan generated by OpenAI's GPT.
    """
    try:
        # Establish MySQL database connection
        connection = mysql.connector.connect(
            host='localhost',  
            database='workout_db', 
            user='your_username',   
            password='your_password' 
        )

        if connection.is_connected():
            cursor = connection.cursor(dictionary=True)
            query = "SELECT height, weight, bmi, goals, intensity, age, gender, duration, experience FROM user_data LIMIT 1"
            cursor.execute(query)
            data = cursor.fetchone()

            if data:
                # Convert metric values to imperial
                height_inches = round(data['height'] * 0.393701, 2)
                weight_pounds = round(data['weight'] * 2.20462, 2)

                # Generate prompt for OpenAI
                system_message = {
                    "role": "system",
                    "content": f"""You are an AI-powered workout coach. Based on the following user data, generate the best possible workout plan for them:
                    
                    Height: {height_inches} inches
                    Weight: {weight_pounds} pounds
                    BMI: {data['bmi']}
                    Goals: {data['goals']}
                    Intensity Level: {data['intensity']}
                    Age: {data['age']}
                    Gender: {data['gender']}
                    Duration: {data['duration']} minutes per session
                    Average Heart Rate: {data['heart_rate']} bpm"""
                }

                # OpenAI API call to generate the workout plan
                response = openai.ChatCompletion.create(
                    model="gpt-4o-mini",
                    messages=[system_message],
                    max_tokens=1000
                )
                workout_plan = response['choices'][0]['message']['content']
                return workout_plan

            else:
                return "User data not found in the database."

    except Error as e:
        return f"Error connecting to MySQL: {e}"
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()